### ISSUE TITLE
b2d-start with errors in 3.0-rc3

### ISSUE THREAD

**Issue by alfert** [tknerr/bills-kitchen#104]
Hi Torben, 

running the bd2-start script results in some error message: 

    W:\>b2d-start
    error in run: Failed to get machine "boot2docker-vm": machine does not exist (Did you run `boot2docker init`?)
    Making sure the boot2docker VM is stopped...
    error in run: Failed to get machine "boot2docker-vm": machine does not exist (Did you run `boot2docker init`?)
    Adding shared folder "billskitchen" for hostpath
    VBoxManage.exe: error: Could not find a registered machine named 'boot2docker-vm'
    VBoxManage.exe: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001),   component VirtualBox, interface IVirtualBox, callee IUnknown
    VBoxManage.exe: error: Context: "FindMachine(Bstr(a->argv[1]).raw(), machine.asOutParam())" at line 919 of file VBoxManageMisc.cpp
    Bringing up the boot2docker VM...
    Latest release for github.com/boot2docker/boot2docker is v1.6.0
    Downloading boot2docker ISO image...

The VM is created but as two problems:

* shared folder `billskitchen` is not created, but it exists one for my home directory
* VBox states that two many virtual cpus are created: In their opinion my machine has only 4 but  not 8 cores. 

Cheers, 
Klaus.

**Comment by alfert** [comment]
Something nasty with the `BK_ROOT` happens: 
   
    BK_ROOT_CYGPATH=\=/
    BK_ROOT_DRIVE=\=/ 
    BK_ROOT_FWD_SLASH=\=/
    BOOT2DOCKER_DIR=W:\home\.boot2docker

Scriptsdir looks fine: 

    SCRIPTSDIR=W:\tools\scripts

After that, the output of `b2d-start` is: 

    Adding shared folder "billskitchen" for hostpath
    VBoxManage.exe: error: Missing argument to '--hostpath'
    Bringing up the boot2docker VM...
    Virtual machine boot2docker-vm already exists
    Waiting for VM and Docker daemon to start...
    .........o 
    Started.
    Writing W:\home\.boot2docker\certs\boot2docker-vm\ca.pem
    Writing W:\home\.boot2docker\certs\boot2docker-vm\cert.pem 
    Writing W:\home\.boot2docker\certs\boot2docker-vm\key.pem
    Your environment variables are already set correctly.

    Mounting the shared folder inside the VM to \=/
    mount.vboxsf: mounting failed with the error: No such file or directory
    mount: mounting billskitchen on =/ failed: No such file or directory
    error in run: exit status 1
    making sure no proxy is set in the boot2docker VM...

**Comment by tknerr** [comment]
There is definitely an issue with the first time downloading of the boot2docker .iso + boot2docker init, looking at the `b2d-start` script i see where it fails. Should be easy to fix.

The weirder issue is with the BK_ROOT dir, but it's a clear bug as well, introduced when I removed the `SCRIPT_DIR` env var [here](https://github.com/tknerr/bills-kitchen/commit/8ca233e3e68b1a6f2466b1a943c7ba18b61f1294#diff-12dab29d29082d2408d91ad01e4080e6L7)

Workaround is to remove this line:
https://github.com/tknerr/bills-kitchen/blob/master/files/tools/scripts/b2d-start.bat#L18

Then run `b2d-stop` and `b2d-start` again and it should work (crossing fingers ;-))

**Comment by alfert** [comment]
Can the workaround really work? The BK_ROOT is then not set, but it is used
later on.

2015-05-05 18:21 GMT+02:00 Torben Knerr <notifications@github.com>:

**Comment by tknerr** [comment]
It's set in the `set-env.bat` script already:
https://github.com/tknerr/bills-kitchen/blob/master/files/set-env.bat#L7

(I moved it there, but forgot to update the `b2d-start` script)

**Comment by alfert** [comment]
Workaround works, thanks!

**Comment by alfert** [comment]
creating the vm via `b2d init`, followed by `b2d-start` gives less errors but still billskitchen is not mounted properly.

    Mounting the shared folder inside the VM to /w/
    mount.vboxsf: mounting failed with the error: No such file or directory
    mount: mounting billskitchen on /w/ failed: No such file or directory
    error in run: exit status 1

**Comment by tknerr** [comment]
oh yes, I can totally reproduce that now

**Comment by tknerr** [comment]
@alfert this should fix your last problem: 0f045cd69fe606e3ae6cce6d8b352414dc7379ed

PR in progress..
