### ISSUE TITLE
.exe files missing in project

### ISSUE THREAD

**Issue by vincentclaes** [tknerr/bills-kitchen#141]
When launching Launch ConEmu.lnk is get a message  "tools/conemu/ConEmu.exe is missing" and i cant find it on the github repository.

I followed the readme, am i missing something? can you doublecheck if it's available?

thx

**Comment by tknerr** [comment]
Hi @vincentclaes, be warned that bills-kitchen is no longer actively maintained (I'm on macOS in the meanwhile...), so as you likely noticed the tool versions are a bit out of date (if you plan to update these I'm happy to accept PRs for sure!) 

Nevertheless, let me try to help / debug this with you:

1. did you take the latest pre-built zip from the releases page, or build it on your own using the rake tasks?
2. does the `tools/conemu/ConEmu.exe` actually exist (in the .zip file or in case you built it yourself in the `target` directory)?

**Comment by vincentclaes** [comment]
thanks for you fast reply! in the mean time i found out i need to download the .7z file. this file contains the .exe files. the .zip file does not contain the .exe files.

cheers.

vincent
