### ISSUE TITLE
Switch to Atom in favor of SublimeText trial version

### ISSUE THREAD

**Issue by tknerr** [tknerr/bills-kitchen#67]
Currently we are bundling SublimeText (trial version), for which we have written consent that this is okay if the package is used for workshops, trials, etc.

However, it still forces the user to obtain a SublimeText license, which is probably well invested but might also be blocking people from using it.

Atom.io looks quite similar and is a truly open source and free alternative:
https://atom.io/

Right now it can not be made portable for windows, though:
https://github.com/atom/atom/issues/2939

Once this is fixed it should replace SublimeText in Bills Kitchen

**Comment by tknerr** [comment]
Woooot, https://github.com/atom/atom/issues/2939 just got fixed!

Let's wait for the next release, then...

**Comment by paul42** [comment]
I actually had an issue trying to use the 'data bag' feature of knife and the extension (Knife-solo_data_bag gem) while working with chef, attempting to set atom as the editor in the knife.rb file wasn't working as I would have expected. namely when I would use the atom as the editor it would open a temporary file that would not function properly as a data bag and would fail validation - when I set my editor to notepad (or notepad++ via the full escaped path) it worked fine, both for normal and encrypted data bags utlizing knife solo data bag plugin.

I do not know if this is just windows, or if it's windows/atom, or if it's windows/atom/knife-solo_data_bag gem. It's not a huge deal, but if someone complains about data bags afterwards, it might be this

**Comment by tknerr** [comment]
Hi @paul42, thanks for letting me know.

I noticed that `git config -e` for example did not work either, until I added the `--wait` flag in 981b6f6de6113fd2aefabcb4579a188912f35943. This should cover it, hopefully.

**Comment by tknerr** [comment]
Released in 3.0-rc1
https://github.com/tknerr/bills-kitchen/releases/tag/3.0-rc1
