### ISSUE TITLE
is rake build stalling? Win7 + Windows Powershell

### ISSUE THREAD

**Issue by paul42** [tknerr/bills-kitchen#80]
Hi, sorry if this is a bit out of the ordinary for an issue, but I'm a touch confused on the install directions, I've installed ruby and ruby dev kit to get the install going, and when I run rake build (after successful returns from gem install bundler and bundle install) it goes for a long bit and seems to 'stall' but I don't know if this is just taking a long time? is there any way to cancel and re-run the command in a more verbose manner?

I'm very new to ruby and chef, thanks for taking the time to read
-Paul
![rakebuildstall](https://cloud.githubusercontent.com/assets/278262/6535243/b77cd532-c400-11e4-88ea-2331d96a9d13.PNG)

**Comment by paul42** [comment]
I think I just didn't wait long enough, after looking at releases, the tests take like 15 minutes. I'm still getting errors so I'm going to open a correct issue.

**Comment by tknerr** [comment]
Hi @paul42, yes it might take a while the first time you run `rake build` because it downloads all the installers. Subsequent runs should be faster as the downloads are cached in the `target/cache` directory.

Let me have a look on the other issue...

**Comment by tknerr** [comment]
Btw: as you mention PowerShell in the title: I was about to remove the `set-env.ps1` script because I'm not using powershell. While I was trying to keep it up-to-date and in sync with `set-env.bat` I admit that I never really tested it.

See here: https://github.com/tknerr/bills-kitchen/issues/73

(and P.S.: I'm seeing some "The system cannot find the path specified" errors in your screenshot above which should definitely not be there)

**Comment by tknerr** [comment]
For the record, just tested against master: both `rake build` as well as `rake acceptance` succeeds on my Win7 machine in a plain cmd shell. 

P.S.: the acceptance tests took 30 minutes (which includes download of at least to baseboxes, some bundle installs as well as setting up some VMs and test them using kitchenci)

**Comment by paul42** [comment]
Yeah, I tried it again over the weekend and it ran for 102 min in powershell hanging at the area. when i finally terminated I could not find any build file or log that had useful info. I'll try rebuilding from cmd.exe and see if that changes. (Thank you for your help btw.)

**Comment by tknerr** [comment]
Ok, let me know how it goes. FYI `rake build` takes ~10-20 minutes on my machine
