### ISSUE TITLE
Vagrant-Workflow-tests fail on release 2.3 on win7

### ISSUE THREAD

**Issue by paul42** [tknerr/bills-kitchen#81]
I downloaded the release and did the git clone for tests and these are the errors I'm getting - is there a way I can build native ruby to avoid these native gem builds failing? 

Failures:

  1) usage scenarios developing top-level cookbooks installs gem dependencies via `bundle install`
     Failure/Error: cmd_succeeds("cd #{APP_COOKBOOK_DIR} && bundle install")

       expected true
            got false
     # ./spec/helpers.rb:33:in `cmd_succeeds'
     # ./spec/acceptance/usage_scenarios_spec.rb:46:in `block (3 levels) in <top (required)>'

  2) usage scenarios developing top-level cookbooks runs the unit tests via `rake test`
     Failure/Error: cmd_succeeds("cd #{APP_COOKBOOK_DIR} && rake test")

       expected true
            got false
     # ./spec/helpers.rb:33:in `cmd_succeeds'
     # ./spec/acceptance/usage_scenarios_spec.rb:49:in `block (3 levels) in <top (required)>'

  3) usage scenarios developing top-level cookbooks runs the integration tests via `rake integration`
     Failure/Error: cmd_succeeds("cd #{APP_COOKBOOK_DIR} && rake integration")

       expected true
            got false
     # ./spec/helpers.rb:33:in `cmd_succeeds'
     # ./spec/acceptance/usage_scenarios_spec.rb:52:in `block (3 levels) in <top (required)>'

Finished in 13 minutes 52 seconds (files took 0.33793 seconds to load)
15 examples, 3 failures

Failed examples:

rspec ./spec/acceptance/usage_scenarios_spec.rb:45 # usage scenarios developing top-level cookbooks inst alls gem dependencies via `bundle install`
rspec ./spec/acceptance/usage_scenarios_spec.rb:48 # usage scenarios developing top-level cookbooks runs  the unit tests via `rake test`
rspec ./spec/acceptance/usage_scenarios_spec.rb:51 # usage scenarios developing top-level cookbooks runs  the integration tests via `rake integration`

W:\repo\vagrant-workflow-tests>

also is there a way to do this for the 'rake build' from source? I love the tail on acceptance.log, and was wondering if there is one for the rake build in the source file?

**Comment by tknerr** [comment]
@paul42 hard to say what's going wrong here. Can you provide the contents of the acceptance.log (e.g. via gist) so I can have a further look?

And are you using powershell or plain cmd shell?

Not sure if I got your last question right, but what I'm usually doing is this:

 * `git clone https://github.com/tknerr/bills-kitchen.git`
 * `git checkout master`
 * `rake build`
 * (going for a coffee)
 * `rake acceptance`
 * (...and another coffee)

No, for the `rake build` there is not a more detailed logfile... :-/

**Comment by tknerr** [comment]
P.S.: you can also use the Ruby DevPack for building bill's kitchen:
https://github.com/tknerr/ruby-devpack/releases/tag/v0.3

**Comment by paul42** [comment]
I'm going to close this issue because I made a giant mistake and did rake acceptance against the wrong folder, I had to terminate the batch for a rake build and in that folder I ran the acceptance test, mistakenly thinking it had finished. I'm still not successfully getting past rake build

**Comment by tknerr** [comment]
@paul42 let me know how it goes and please reoepen if you have further problems with the acceptance tests

Btw this is what `rake acceptance` does:
https://github.com/tknerr/bills-kitchen/blob/master/Rakefile#L65-69

And same here: the first time after a `rake build` of the bills-kitchen devpack it will take quite long for the acceptance tests to finish. If you run them a second time they will be much faster since all the vagrant baseboxes are already downloaded, bundled gems already installed, and much more will be already cached. (see `target/build/home/vagrant.d/boxes` and `target/build/home/vagrant.d/cache` for example)
