### ISSUE TITLE
unable to complete build from source in cmd.exe win 7 

### ISSUE THREAD

**Issue by paul42** [tknerr/bills-kitchen#82]
Create new issue since I made mistakes on the past two (sorry :[ )

1.) Got and installed ruby-devpack release successfully. 
2.) mounting ruby dev pack on X:\ and using set-env successfully
3.) rake build in cmd fails (https://gist.github.com/paul42/0684a80da8981fbf4992#file-rake-build-errors) the rake build actually finishes now! but it's got a ton a failures
4.) Attempting build in git bash, then I'll attempt build in powershell to see if there are any noticeable differences

**Comment by paul42** [comment]
Powershell still hangs... going to abandon for now and attempt to set git bash ruby to /x/tools/..... and try rake build again...
after looking at the gist I'm wondering if I just need to find a way to install those consul/packer/terraform programs from hashi corp

**Comment by paul42** [comment]
verified that all links in rakefile "def download_tools" point to downloads, but not certain at what point items are going wrong and not getting unpacked

**Comment by paul42** [comment]
actually watched the beginning of the rake build instead of walking away, found that there are a bunch of path not found errors: https://gist.github.com/paul42/477a53b2f178617ceb2f

**Comment by paul42** [comment]
cleared out my temp folder. building with fresh git clone from cmd.exe.
-current assumption: first botched powershell build grabbed files, put them in cache, and something mangled something else so cache retrieval is now state:borked.

**Comment by paul42** [comment]
still having failures even after deleting entire AppData\local\temp\ innards 
https://gist.github.com/paul42/b49cd9d93f4c883e7ae5
This is a long gist, Not pictured: launched conemu from link, so it set the environment for me. pictured: from the git clone to the rake build. Still seeing a myriad of path not found errors.

any help is appreciated. thanks in advance, 
Paul

**Comment by tknerr** [comment]
Hi @paul42, I'm sorry this turns out so troublesome for you. 

Just to reassure: do you need to build bills-kitchen from source via `rake build`? Or can you just grab the lastest binary 2.3 release from the [releases page](https://github.com/tknerr/bills-kitchen/releases)? 

I'm asking because I noticed that installation instructions in the README refer to building from source only, but do not mention the releases page. I have to be more clear about that...

But anyway, you should definitely be able to build it from source. Let me try to reproduce this with a clean ruby devpack and freshly cloned bills-kitchen repo, same as you did...

**Comment by paul42** [comment]
I'll try to pull the release and use that, I wasn't certain if I should use that due to native extensions or something, still learning a lot in this area.

my desired use case is to make it as simple as possible for the other workers on my team to use ruby/chef so we can start migrating our infrastructure to open stack via config-capture.

Thanks for your time, I've certainly learned a ton already, so that's good :) also using conEmu as my default because it's pretty snazzy.

**Comment by paul42** [comment]
ah, worked like a charm! yes I would definitely mention using the releases as a more expedient method, if you don't have a ruby environment set up already. I was able to download and install knife-openstack gem (which I could never successfully do on windows previously) and connected to our instance easy as pie.

THANK YOU very much for making a dev pack like this! since I've installed a custom gem (knife-openstack) is there a way for me to 'repackage' it back to zip form or will I just have to instruct my colleagues to install it? would rake package work or is that something different?

**Comment by tknerr** [comment]
Glad that the binary release works for you. I will mention that on the README more explicitly, sorry for the confusion that it caused.

Still weird that the build from source did not work for you. I just re-ran it and it finished without errors. Strange :-/

Concerning the knife-openstack gem: Yes, you can simply repackage it to make it easier for your colleagues. Everything you do in the `set-env`ed bills-kitchen devpack should happen inside the devpack (i.e. the mounted directory). This applies to any gems you install, baseboxes you downloaded, etc.. 

For example, if you repackage the devpack *after* running the acceptance tests it will be "preloaded" with all the packages, gems, baseboxes that were downloaded during the acceptance test. It might make sense to do that kind of "preloading" before distributing the package to your team: 1) it will be less error prone (vanishing urls etc) and 2) you will save them precious download and installation time

**Comment by tknerr** [comment]
Another hint regarding the errors you got: run `rake build --trace` to enable stacktraces, that might reveal some additional details for troubleshooting

**Comment by tknerr** [comment]
FYI - updated the README to be more clear on the installation instructions. Should be much more clear now:
https://github.com/tknerr/bills-kitchen/blob/master/README.md#installation-and-usage

**Comment by paul42** [comment]
I'm guessing this is more specific to just my machine and environment. this isn't really an issue since the release works fine and is preferable.
