### ISSUE TITLE
conemu.exe missing?

### ISSUE THREAD

**Issue by milh0use** [tknerr/bills-kitchen#99]
Are we meant to download it ourselves and place it in tools/conemu?

**Comment by tknerr** [comment]
Did you try to build from source [as described here](https://github.com/tknerr/bills-kitchen#building-bills-kitchen), or download [release package](https://github.com/tknerr/bills-kitchen/releases)?

**Comment by milh0use** [comment]
Ah, sorry. I did a git clone and forgot that put me in the "building from source" group... I'll grab the zip file.

**Comment by tknerr** [comment]
@milh0use yeah, the releases page with the zip files is not immediately obvious. I'm currently uploading 3.0-rc3, which has some more improvements (especially if you are working with docker) and bugfixes. You might want to grab that version once it's up.

**Comment by tknerr** [comment]
...and its up now: https://github.com/tknerr/bills-kitchen/releases/tag/3.0-rc3
